language: java

jdk:
- oraclejdk8

install: "./gradlew assemble"

after_success: .buildscript/deploy_snapshot.sh

branches:
  except:
    - gh-pages

notifications:
  email: false

env:
  global:
    - secure: "ozD0VNLXZXKqUQTIPJJEldR8VNJba2c5FbUO25pJS4yunBKon7NGrsgX53db/Ffey+LZlM3iaLDak/L4dBqDJMY1usR/RJdluiutH9f9xUY2sFxqptxt85x/7b/Saw1Sn9VTQCrHZM+WcpfmfBfu7xszArIMkPH83NdyjBYH4kRFz7hQokSW1c/xlu+0omholpNmOpvKp56D0SH8J64bE5Kw2sOtvxw1CYJ5YFSk9M5PtOTQvweYkrqQ3pxED25u2lyRo/BF9EKSqiPeJeRU3l+jAYCnxHjgZh9IbzlAcadsOyMrIkGWyL21DKmcl20ylTjLqsTn2Fo53lRLNc/x4rlhtWgQ0ln391hGrt6fKH67kDaC72xc0UJSZ2+MNYJ6kbNkQNyJnrFZ+Zi5mUI8P41kU9iaJ+F0lsB0pPtHmL/poh7k6QtDqyaBjhc7cZ7a8+W+kpLl0iU/YfK3LRrWVP9ilYV6uviTLDv5D2mLxeZ8UlmsmiST8QAfXuzohAveWqyOhKm/J4QT8Q9BTRD3nNX1JCyhBKAX8KGhsCsT44dst6WlTq++oO/7BhYcuAgel0MzFi/3MatyVkUZLyVZekhZR/2O2WxEao5rCMtTOv9BZBhSi+/9O/QQbqZvxbGOjRi/IlcUtMFE/GqPL+qSvyPUP6PbLX13TAuhvSmm/EQ="
    - secure: "OVC1zfknLzqnYDBWBKYbPYf0n4y6ObTp8awg2sVpfdcnoWSa+dPdT98aYtEytnrOVVUHsauQUYhI9+uzJWvEvPT0+jQCE9Xu1NOcm1e6usf19sZERi2GtpI4NzPTXMsgmUC/ye1Ij41RRUclwy7OdVyLEAqqhOJ2HeA/XcYgbE5kJThmw6nDyzo7zKfyMWgVXI66OqKoZiiZ5CBUkT2yzQw/MyYU8DISr6XbMWpYDpHJkopUzyOzTRqtSXLONJ9virCdazMzwUL4nA/uGEcaHtgHYEsFstrMMqjO9041kLeXvBOcJ8bQBaTRgcTYYqGt/LEpysTqdc9Jg0KZnflEKc3kY/L+KMnvXHfCQaKW+jvMcyOZ7RN+r3UpTH8fmzFE65GLCcbbVRouNrxwoqzwf0XfrCHP6kO2W37d0Ky53y6PU/m4DB+Cgf4QnFUJeeinqpW/8La4mi3ttzGambs83z0oL6tyWx0UmG1C1bghvd71pCLqFk/yyQaLc3Gjqv8ZncbHYtWh9O0Ys06UCWoCPtnW9Oo+/uYCMZEw14tJm5zsNugyUTD55Ppm4/TRw6HF7z6Hdilk9JYdJ0IMh+WAfNPRyQ0zxWJ9Dssz8TNExtbjiytzTHzPwxoEf2Lp19lCVzyUedQZgxibzUjicEHx1MmkdCBscsnNnm0dSj8IToc="

